# Generated by Django 5.0.1 on 2024-01-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10)),
                ('rom', models.SmallIntegerField()),
                ('ram', models.SmallIntegerField()),
                ('color', models.CharField(max_length=7)),
                ('is_new', models.BooleanField()),
                ('weight', models.FloatField()),
                ('dimension', models.FloatField()),
                ('battery_capacity', models.SmallIntegerField()),
                ('operating_system', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
