# Generated by Django 5.0.1 on 2024-01-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('engine', models.FloatField()),
                ('seats', models.SmallIntegerField()),
                ('production_year', models.TimeField()),
                ('is_new', models.BooleanField()),
                ('painted_part', models.CharField(max_length=10)),
                ('oil_sort', models.CharField(max_length=7)),
            ],
        ),
    ]
