# Generated by Django 5.0.1 on 2024-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(default='sedan', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.DateTimeField(),
        ),
    ]
